### ISSUE TITLE
Cannot form weak reference to instance (0x7fe59aa0e590) of class AFWebViewController. It is possible that this object was over-released, or is in the process of deallocation.的报错

### ISSUE THREAD

**Issue by honeybeeSwinging** [Fogh/AFWebViewController#14]
报错：Cannot form weak reference to instance (0x7fe59aa0e590) of class AFWebViewController. It is possible that this object was over-released, or is in the process of deallocation.

断电定位在：_webView.navigationDelegate = self;

**Comment by Fogh** [comment]
Sorry for the very late answer. `self.webview.navigationDelegate` is being set to nil in `dealloc`, but that is probably not needed anymore. So it can be fixed by removing this line: 

https://github.com/Fogh/AFWebViewController/blob/master/AFWebViewController/AFWebViewController.m#L84
