### ISSUE TITLE
viewDidDisappear: causes network indicator to appear 

### ISSUE THREAD

**Issue by mstepniczka** [Fogh/AFWebViewController#5]
I believe [UIApplication sharedApplication].networkActivityIndicatorVisible = YES was meant to = NO in that method.

**Comment by Fogh** [comment]
That is correct! I just fixed that.

**Comment by ssoper** [comment]
Can we get a bump in the podspec so we can bring this fix in? Much appreciated :boat:

**Comment by Fogh** [comment]
I just bumped the podspec to 1.0.4 :+1:

**Comment by ssoper** [comment]
thank you!
