### ISSUE TITLE
Back/Foward button image invisible(cocoapod + swift)

### ISSUE THREAD

**Issue by seapy** [Fogh/AFWebViewController#6]
Back/Foward button image invisible.

my project use cocoapods + swift
used AFWebViewController version : 1.0.4

i think this issue will help you.
https://github.com/TransitApp/SVWebViewController/pull/131/files

**Comment by Fogh** [comment]
Yes, this should be fixed. 

If you have a solution, a pull request would be appreciated :smiley:
